In [1]:
import pandas as pd
df=pd.read_csv("titanic.csv")

In [2]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df.drop(['Name','SibSp','Parch','Ticket','Fare','Cabin','Embarked'],axis=1,inplace=True)

In [4]:
df

     PassengerId  Survived  Pclass     Sex   Age
0              1         0       3    male  22.0
1              2         1       1  female  38.0
2              3         1       3  female  26.0
3              4         1       1  female  35.0
4              5         0       3    male  35.0
..           ...       ...     ...     ...   ...
886          887         0       2    male  27.0
887          888         1       1  female  19.0
888          889         0       3  female   NaN
889          890         1       1    male  26.0
890          891         0       3    male  32.0

[891 rows x 5 columns]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
input=df.drop(["Survived"],axis=1)	
input

     PassengerId  Pclass     Sex   Age
0              1       3    male  22.0
1              2       1  female  38.0
2              3       3  female  26.0
3              4       1  female  35.0
4              5       3    male  35.0
..           ...     ...     ...   ...
886          887       2    male  27.0
887          888       1  female  19.0
888          889       3  female   NaN
889          890       1    male  26.0
890          891       3    male  32.0

[891 rows x 4 columns]

In [8]:
target=df.Survived
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [9]:
input

     PassengerId  Pclass     Sex   Age
0              1       3    male  22.0
1              2       1  female  38.0
2              3       3  female  26.0
3              4       1  female  35.0
4              5       3    male  35.0
..           ...     ...     ...   ...
886          887       2    male  27.0
887          888       1  female  19.0
888          889       3  female   NaN
889          890       1    male  26.0
890          891       3    male  32.0

[891 rows x 4 columns]

In [11]:
input.Sex=input.Sex.map({"male":1, "female":2})
input

     PassengerId  Pclass  Sex   Age
0              1       3    1  22.0
1              2       1    2  38.0
2              3       3    2  26.0
3              4       1    2  35.0
4              5       3    1  35.0
..           ...     ...  ...   ...
886          887       2    1  27.0
887          888       1    2  19.0
888          889       3    2   NaN
889          890       1    1  26.0
890          891       3    1  32.0

[891 rows x 4 columns]

x_train,x_test,y_train,y_test=train_test_split(input,target,test_size=0.2)

In [12]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [18]:
from sklearn import tree

In [22]:
model=tree.DecisionTreeClassifier()

In [24]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [27]:
y_predicted=model.predict(x_test)
y_predicted

array([0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0])

In [29]:
model.score(x_test,y_test)

0.7541899441340782